package com.waseel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UhudInterface", targetNamespace = "http://www.waseel.com/wsdl/primary/wschema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UhudInterface {

	/**
	 * 
	 * @param requestObject
	 * @return returns com.waseel.TransactionWrapper
	 */
	@WebMethod
	@WebResult(name = "TransactionWrapper", targetNamespace = "http://www.waseel.com/wsdl/primary/wschema", partName = "responseObject")
	public TransactionWrapper submitSchema(
			@WebParam(name = "TransactionWrapper", targetNamespace = "http://www.waseel.com/wsdl/primary/wschema", partName = "requestObject") TransactionWrapper requestObject);

}
