package com.waseel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Uhud service = new Uhud();
 * UhudInterface portType = service.getUhudInterfacePort();
 * portType.submitSchema(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Uhud", targetNamespace = "http://www.waseel.com/wsdl/primary/wschema", wsdlLocation = "https://devzero.waseel.com/WaseelSwitch/Uhud/Service?wsdl")
public class Uhud extends Service {

	private final static URL UHUD_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.waseel.Uhud.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.waseel.Uhud.class.getResource(".");
			url = new URL(
					baseUrl,
					//"https://devzero.waseel.com/WaseelSwitch/Uhud/Service?wsdl");
					"https://switch.waseel.com/WaseelSwitch/Uhud/Service?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Muhammad.Tayyab/Workspaces/MyEclipse%202015/healthcover%20Maven%20Webapp/src/main/webapp/WEB-INF/wsdl/Uhud.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		UHUD_WSDL_LOCATION = url;
	}

	public Uhud(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Uhud() {
		super(UHUD_WSDL_LOCATION, new QName(
				"http://www.waseel.com/wsdl/primary/wschema", "Uhud"));
	}

	/**
	 * 
	 * @return returns UhudInterface
	 */
	@WebEndpoint(name = "UhudInterfacePort")
	public UhudInterface getUhudInterfacePort() {
		return super.getPort(new QName(
				"http://www.waseel.com/wsdl/primary/wschema",
				"UhudInterfacePort"), UhudInterface.class);
	}

}
